// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20231102131144_Seed data into Regions and Difficulties")]
    partial class SeeddataintoRegionsandDifficulties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c98811c2-8a75-4f21-9456-6631c26586c2"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("59b2d3a9-58c5-4097-8cd4-6ba2d3ec854a"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("40fc60ab-745b-41ca-911e-f448d26aed2b"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4da9f85-b783-41bc-995f-2f365c57fa13"),
                            Code = "W/R",
                            Name = "Western Region",
                            RegionImageUrl = "https://...anyyyy"
                        },
                        new
                        {
                            Id = new Guid("ac9b24ef-2612-4f74-a543-2acd3720a04c"),
                            Code = "A/R",
                            Name = "Ashanti Region",
                            RegionImageUrl = "https://...anyyyy"
                        },
                        new
                        {
                            Id = new Guid("403ad540-e02a-4f58-b9ad-e0da81aa47cb"),
                            Code = "C/R",
                            Name = "Central Region",
                            RegionImageUrl = "https://...anyyyy"
                        },
                        new
                        {
                            Id = new Guid("30ff8627-7e90-49c5-bd46-428164fee121"),
                            Code = "W/R",
                            Name = "Western Region",
                            RegionImageUrl = "https://...anyyyy"
                        },
                        new
                        {
                            Id = new Guid("2cccdcad-19a4-4195-a2d6-3defdf1aad5e"),
                            Code = "A/R",
                            Name = "Ashanti Region",
                            RegionImageUrl = "https://...anyyyy"
                        },
                        new
                        {
                            Id = new Guid("8a1cf8a6-eb83-4405-92f6-79308ba91497"),
                            Code = "C/R",
                            Name = "Central Region",
                            RegionImageUrl = "https://...anyyyy"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
